# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest

    steps:
      
    - name: "Cache: Cywgin Repository"
      uses: actions/cache@v3
      with:
        path: "C:/cygwin-packages"
        # https://github.com/actions/cache/issues/342#issuecomment-673371329
        key: ${{ runner.os }}-cygwin-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-cygwin-

    - name: "Install: Cygwin"
      uses: cygwin/cygwin-install-action@master
      with:
        packages: openssh
        
    - name: "Create Windows testuser"
      shell: powershell
      run:
        $username = "testuser"
        $password = "P@ssw0rd"
        $passwordEncrypted = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name $username -Password $passwordEncrypted
      
    - env:
        CYGWIN: "binmode ntsec"
      run: |
        echo $OSTYPE
        ssh-keygen -A # generate host keys
        #sshd -D -p 2222 -o User=mytestuser -o PermitRootLogin=false
