# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

defaults:
  run:
    shell: bash

env:
  TEST_SSH_HOST: 127.0.0.1
  TEST_SSH_PORT: 2222
  TEST_SSH_USER: testuser
  TEST_SSH_KEY_FILE: test/id_key.txt
  TEST_SSH_PUB_FILE: test/id_pub.txt
  TEST_SSH_PW: MySuperPW123

jobs:
  build:
    runs-on: windows-latest

    steps:

    - run: |
        choco install openssh
        "$PROGRAMFILES/OpenSSH-Win64/ssh-keygen" -A
        "$PROGRAMFILES/OpenSSH-Win64/sshd" -D -ddd
