# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

defaults:
  run:
    shell: bash

env:
  TEST_SSH_HOST: 127.0.0.1
  TEST_SSH_PORT: 2222
  TEST_SSH_USER: testuser
  TEST_SSH_PW: MySuperPW123

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: "Cache: Cywgin Repository"
      uses: actions/cache@v3
      with:
        path: |
          "C:/cygwin"
          "C:/cygwin-packages"
        # https://github.com/actions/cache/issues/342#issuecomment-673371329
        key: ${{ runner.os }}-cygwin-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-cygwin-

    - name: "Install: Cygwin"
      uses: cygwin/cygwin-install-action@master
      with:
        packages: expect openssh

    - name: "Create Windows testuser for SSH"
      shell: powershell
      run: |
        $username = "${{ env.TEST_SSH_USER }}"
        $password = "${{ env.TEST_SSH_PW }}"
        $passwordEncrypted = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name $username -Password $passwordEncrypted

    - env:
        CYGWIN: "binmode ntsec"
        SHELLOPTS: "igncr"
      run: |
        set -eux

        chmod 400 $(pwd)/test/*

        ssh-keygen -A # generate host keys
        cat <<EOF > /etc/sshd_config
        ListenAddress 127.0.0.1
        Port 2222
        PermitRootLogin no
        StrictModes no
        PubkeyAuthentication yes
        AuthorizedKeysFile $(pwd)/test/id_pub.txt
        IgnoreUserKnownHosts yes
        PasswordAuthentication yes
        PermitEmptyPasswords no
        EOF

        sshd -dd &

        ssh testuser@127.0.0.1 -i $(pwd)/test/id_key.txt -P 2222 -c "whoami"

    - name: Remove cygwin/msys2 tar binaries
      shell: bash
      run: |
        # https://github.com/actions/cache/issues/1073
        rm -rfv /usr/bin/tar "/cygdrive/c/Program Files/Git/usr/bin/tar.exe"
