# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

defaults:
  run:
    shell: bash

env:
  TEST_SSH_HOST: 127.0.0.1
  TEST_SSH_PORT: 2222
  TEST_SSH_USER: testuser
  TEST_SSH_PW: MySuperPW123

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Create Windows testuser for SSH"
      shell: powershell
      run: |
        $username = "${{ env.TEST_SSH_USER }}"
        $password = "${{ env.TEST_SSH_PW }}"
        $passwordEncrypted = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name $username -Password $passwordEncrypted

    - run: |
        set -eux

        chmod 400 $(pwd)/test/*

        ssh-keygen -A # generate host keys
        cat <<EOF > /etc/sshd_config
        ListenAddress 127.0.0.1
        Port 2222
        PermitRootLogin no
        StrictModes no
        PubkeyAuthentication yes
        AuthorizedKeysFile $(pwd)/test/id_pub.txt
        IgnoreUserKnownHosts yes
        PasswordAuthentication yes
        PermitEmptyPasswords no
        EOF
        cat /etc/sshd_config
        dos2unix /etc/sshd_config

        /usr/bin/sshd -dd &

        ssh testuser@127.0.0.1 -i $(pwd)/test/id_key.txt -p 2222 -c "whoami"
